[package]
name = "simplebase"
license = "MIT"
version = "0.2.1"
authors = ["Arthur Givney <agiv888@gmail.com>"]
description = "A simple to use database library with no dependencies"
keywords = ["database", "simple","simplebase"]
categories = ["database-implementations"]


[dependencies]


